<?php
/**
 * Created by PhpStorm.
 * User: huosheng
 * Date: 2018/1/25
 * Time: 15:46
 */

namespace app\admin\controller;
use think\Controller;

class Category extends Controller
{
    protected $db;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->db =new \app\common\model\Category();
    }

    //首页
    public function index()
    {
        return $this->fetch();
    }
    //添加子栏目
    public function store()
    {
        if(request()->isPost())
        {
//            halt(input('post.'));
            //交给模型处理
            $res =$this->db->store(input('post.'));
            if($res['valid'])
            {
                //操作成功
                $this->success($res['msg'],'index');exit;
            }else{
                $this->error($res['msg']);exit;
            }

        }
        return $this->fetch();
    }


}